package akunevich.pullrequest.settings;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;

public class SettingsForm {
    private JTextField url;
    private JTextField username;
    private JPasswordField password;
    private JPanel panel;

    private Settings settings;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    public void create(Settings settings) {
        this.settings = settings;

        url.setText(settings.getUrl());
        username.setText(settings.getUsername());
        password.setText(settings.getPassword());
    }

    public void apply() {
        settings.setUrl(url.getText());
        settings.setUsername(username.getText());
        settings.setPassword(String.valueOf(password.getPassword()));
    }

    public void reset() {
        url.setText(settings.getUrl());
        username.setText(settings.getUsername());
        password.setText(settings.getPassword());
    }

    public JPanel getPanel() {
        return panel;
    }

    public void setData(Settings data) {
        url.setText(data.getUrl());
        username.setText(data.getUsername());
        password.setText(data.getPassword());
    }

    public void getData(Settings data) {
        data.setUrl(url.getText());
        data.setUsername(username.getText());
        data.setPassword(password.getText());
    }

    public boolean isModified(Settings data) {
        if (url.getText() != null ? !url.getText().equals(data.getUrl()) : data.getUrl() != null) return true;
        if (username.getText() != null ? !username.getText().equals(data.getUsername()) : data.getUsername() != null)
            return true;
        return password.getText() != null ? !password.getText().equals(data.getPassword()) : data.getPassword() != null;
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        url = new JTextField();
        panel.add(url, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        username = new JTextField();
        panel.add(username, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        password = new JPasswordField();
        panel.add(password, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }


}
